services:
  # T-frog モータドライバとの通信プロセス
  ypspur:
    build: .
    privileged: true
    volumes:
      - /dev:/dev
    command: >
      bash -c "
        /ws/install/yamabico_driver/share/yamabico_driver/scripts/ypspur_coordinator_bridge
        /ws/install/yamabico_driver/share/yamabico_driver/config/beego.param
      "
    network_mode: host

  # yamabico_driver ROS2 ノード（モーター制御 + odom）
  driver:
    build: .
    depends_on:
      - ypspur
    command: ros2 run yamabico_driver yamabico_driver
    network_mode: host

  # URG LiDAR ノード
  urg:
    build: .
    privileged: true
    volumes:
      - /dev:/dev
    command: ros2 launch yamabico_driver urg_launch.py
    network_mode: host
